import { motion } from "framer-motion";
import { block, imageUrl, str, templateLabel, type NeoSite } from "../lib/neoSite";

/**
 * Renders Neo's ACTUAL generated site, not our invented copy.
 *
 * The content, images, headline and product names below all come from Neo's own generator
 * (see src/lib/neoSite.ts). We are not building a site here — we are showing what Neo would
 * build, which is the whole point of the repositioning: they generate, we qualify.
 *
 * Deliberately a compact card, not a full site render. The reveal's headline is the domain and
 * the mailboxes — that is our differentiator — and a full-bleed site preview would push them
 * below the fold. This is enough to be convincing and no more.
 */
export default function NeoSitePreview({
  site,
  delay = 0,
}: {
  site: NeoSite;
  delay?: number;
}) {
  const header = block(site, "header");
  const intro = block(site, "introduction");
  const products = block(site, "products");

  const heroUrl = imageUrl(site, (intro as any)?.desktopCoverImage ?? (intro as any)?.image);
  const title = str(header, "title") ?? "Your site";
  const heading = str(intro, "heading");
  const description = str(intro, "description");
  const cta = ((intro as any)?.mainButton?.buttonLabel as string) ?? null;

  const productList = ((products as any)?.productList ?? []) as Record<string, unknown>[];

  return (
    <motion.div
      className="neo-site"
      initial={{ opacity: 0, y: 14 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
    >
      <div className="neo-site-chrome">
        <span className="neo-dot" />
        <span className="neo-dot" />
        <span className="neo-dot" />
        <span className="neo-site-title">{title}</span>
      </div>

      {heroUrl && (
        <div className="neo-site-hero">
          <img src={heroUrl} alt="" loading="lazy" />
        </div>
      )}

      <div className="neo-site-body">
        {heading && <p className="neo-site-heading">{heading}</p>}
        {description && <p className="neo-site-desc">{description}</p>}
        {cta && <span className="neo-site-cta">{cta}</span>}

        {productList.length > 0 && (
          <div className="neo-site-products">
            {productList.slice(0, 3).map((p, i) => {
              const url = imageUrl(site, p.image);
              const name = typeof p.heading === "string" ? p.heading : null;
              return (
                <div className="neo-product" key={i}>
                  {url && <img src={url} alt="" loading="lazy" />}
                  {name && <span>{name}</span>}
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div className="neo-site-foot">
        {/* Honest about provenance. "fixture" means Neo's API didn't answer and we're showing
            a previously recorded real response — worth being able to say out loud. */}
        {/* Precise wording matters here. We show Neo's real generated CONTENT, rendered in our
            own card — not their template layout. And template selection is not deterministic:
            the same description has returned six different templates across runs. So this says
            "content" and "suggested", not "your site will look like this". */}
        <span>
          Content generated by Neo · suggested {templateLabel(site.templateKey)} template
        </span>
        {/* Say it plainly when the live call failed and this is a recorded response. Quietly
            substituting old output for live output is the kind of thing that gets noticed at
            exactly the wrong moment. */}
        {site.source === "fixture" && (
          <span className="neo-site-fallback" title="Neo's generator didn't respond; showing a previously recorded real response">
            offline — recorded earlier
          </span>
        )}
      </div>
    </motion.div>
  );
}
