import { motion } from "framer-motion";
import { block, imageUrl, pickHero, str, templateLabel, type NeoSite } from "../lib/neoSite";

/**
 * Neo's generated site, as a browser-framed snapshot.
 *
 * Matches the generator card: chrome, hero, headline, copy, CTA, three product shots,
 * and a provenance footer. Two of these sit side by side on email+site — both from
 * Neo's generator for this business, not a marketing reel of other shops.
 */
export default function NeoSitePreview({
  site,
  delay = 0,
  avoidHero = null,
  fallbackSite = null,
}: {
  site: NeoSite;
  delay?: number;
  avoidHero?: string | null;
  fallbackSite?: NeoSite | null;
}) {
  const header = block(site, "header");
  const intro = block(site, "introduction");
  const products = block(site, "products");

  const heroUrl = pickHero(site, "landing", avoidHero, fallbackSite);
  const title = str(header, "title") ?? "Your site";
  const heading = str(intro, "heading");
  const description = str(intro, "description");
  const cta = ((intro as { mainButton?: { buttonLabel?: string } } | null)?.mainButton?.buttonLabel) ?? null;
  const productList = ((products as { productList?: Record<string, unknown>[] } | null)?.productList ??
    []) as Record<string, unknown>[];

  return (
    <motion.div
      className="neo-site"
      initial={{ opacity: 0, y: 14 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
    >
      <div className="neo-site-chrome">
        <span className="neo-dot" />
        <span className="neo-dot" />
        <span className="neo-dot" />
        <span className="neo-site-title">{title}</span>
      </div>

      {heroUrl && (
        <div className="neo-site-hero">
          <img src={heroUrl} alt="" loading="lazy" />
        </div>
      )}

      <div className="neo-site-body">
        {heading && <p className="neo-site-heading">{heading}</p>}
        {description && <p className="neo-site-desc">{description}</p>}
        {cta && <span className="neo-site-cta">{cta}</span>}

        {productList.length > 0 && (
          <div className="neo-site-products">
            {productList.slice(0, 3).map((p, i) => {
              const url = imageUrl(site, p.image);
              const name = typeof p.heading === "string" ? p.heading : null;
              if (!url && !name) return null;
              return (
                <div className="neo-product" key={i}>
                  {url && <img src={url} alt="" loading="lazy" />}
                  {name && <span>{name}</span>}
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div className="neo-site-foot">
        <span>Content generated by Neo · suggested {templateLabel(site.templateKey)} template</span>
        {site.source === "fixture" && (
          <span className="neo-site-fallback" title="Neo's generator didn't respond; showing a previously recorded real response">
            offline — recorded earlier
          </span>
        )}
      </div>
    </motion.div>
  );
}
